# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import mvdp.edc_management_client
from mvdp.edc_management_client.api.transfer_process_api import TransferProcessApi  # noqa: E501
from mvdp.edc_management_client.rest import ApiException


class TestTransferProcessApi(unittest.TestCase):
    """TransferProcessApi unit test stubs"""

    def setUp(self):
        self.api = mvdp.edc_management_client.api.transfer_process_api.TransferProcessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deprovision_transfer_process(self):
        """Test case for deprovision_transfer_process

        """
        pass

    def test_get_transfer_process(self):
        """Test case for get_transfer_process

        """
        pass

    def test_get_transfer_process_state(self):
        """Test case for get_transfer_process_state

        """
        pass

    def test_initiate_transfer_process(self):
        """Test case for initiate_transfer_process

        """
        pass

    def test_query_transfer_processes(self):
        """Test case for query_transfer_processes

        """
        pass

    def test_terminate_transfer_process(self):
        """Test case for terminate_transfer_process

        """
        pass


if __name__ == '__main__':
    unittest.main()
