# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import mvdp.edc_management_client
from mvdp.edc_management_client.models.callback_address_dto import CallbackAddressDto  # noqa: E501
from mvdp.edc_management_client.rest import ApiException

class TestCallbackAddressDto(unittest.TestCase):
    """CallbackAddressDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CallbackAddressDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallbackAddressDto`
        """
        model = mvdp.edc_management_client.models.callback_address_dto.CallbackAddressDto()  # noqa: E501
        if include_optional :
            return CallbackAddressDto(
                context = None, 
                type = '', 
                auth_code_id = '', 
                auth_key = '', 
                events = [
                    ''
                    ], 
                transactional = True, 
                uri = ''
            )
        else :
            return CallbackAddressDto(
                events = [
                    ''
                    ],
                uri = '',
        )
        """

    def testCallbackAddressDto(self):
        """Test CallbackAddressDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
