# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import mvdp.edc_management_client
from mvdp.edc_management_client.models.transfer_request_dto import TransferRequestDto  # noqa: E501
from mvdp.edc_management_client.rest import ApiException

class TestTransferRequestDto(unittest.TestCase):
    """TransferRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransferRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferRequestDto`
        """
        model = mvdp.edc_management_client.models.transfer_request_dto.TransferRequestDto()  # noqa: E501
        if include_optional :
            return TransferRequestDto(
                asset_id = '', 
                callback_addresses = [
                    mvdp.edc_management_client.models.callback_address_dto.CallbackAddressDto(
                        @context = mvdp.edc_management_client.models.@context.@context(), 
                        @type = '', 
                        auth_code_id = '', 
                        auth_key = '', 
                        events = [
                            ''
                            ], 
                        transactional = True, 
                        uri = '', )
                    ], 
                connector_address = '', 
                connector_id = '', 
                contract_id = '', 
                data_destination = mvdp.edc_management_client.models.data_address.DataAddress(
                    properties = {
                        'key' : ''
                        }, ), 
                id = '', 
                managed_resources = True, 
                private_properties = {
                    'key' : ''
                    }, 
                properties = {
                    'key' : ''
                    }, 
                protocol = ''
            )
        else :
            return TransferRequestDto(
                asset_id = '',
                connector_address = '',
                connector_id = '',
                contract_id = '',
                data_destination = mvdp.edc_management_client.models.data_address.DataAddress(
                    properties = {
                        'key' : ''
                        }, ),
                protocol = '',
        )
        """

    def testTransferRequestDto(self):
        """Test TransferRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
