# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import mvdp.edc_management_client
from mvdp.edc_management_client.api.data_plane_public_api_api import DataPlanePublicAPIApi  # noqa: E501
from mvdp.edc_management_client.rest import ApiException


class TestDataPlanePublicAPIApi(unittest.TestCase):
    """DataPlanePublicAPIApi unit test stubs"""

    def setUp(self):
        self.api = mvdp.edc_management_client.api.data_plane_public_api_api.DataPlanePublicAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_patch(self):
        """Test case for patch

        """
        pass

    def test_post(self):
        """Test case for post

        """
        pass

    def test_put(self):
        """Test case for put

        """
        pass


if __name__ == '__main__':
    unittest.main()
