# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import mvdp.edc_management_client
from mvdp.edc_management_client.api.contract_agreement_api import ContractAgreementApi  # noqa: E501
from mvdp.edc_management_client.rest import ApiException


class TestContractAgreementApi(unittest.TestCase):
    """ContractAgreementApi unit test stubs"""

    def setUp(self):
        self.api = mvdp.edc_management_client.api.contract_agreement_api.ContractAgreementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_agreement_by_id(self):
        """Test case for get_agreement_by_id

        """
        pass

    def test_query_all_agreements(self):
        """Test case for query_all_agreements

        """
        pass


if __name__ == '__main__':
    unittest.main()
