# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import mvdp.edc_management_client
from mvdp.edc_management_client.api.asset_api import AssetApi  # noqa: E501
from mvdp.edc_management_client.rest import ApiException


class TestAssetApi(unittest.TestCase):
    """AssetApi unit test stubs"""

    def setUp(self):
        self.api = mvdp.edc_management_client.api.asset_api.AssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_asset(self):
        """Test case for create_asset

        """
        pass

    def test_get_asset(self):
        """Test case for get_asset

        """
        pass

    def test_get_asset_data_address(self):
        """Test case for get_asset_data_address

        """
        pass

    def test_remove_asset(self):
        """Test case for remove_asset

        """
        pass

    def test_request_assets(self):
        """Test case for request_assets

        """
        pass

    def test_update_asset(self):
        """Test case for update_asset

        """
        pass

    def test_update_data_address(self):
        """Test case for update_data_address

        """
        pass


if __name__ == '__main__':
    unittest.main()
