# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import mvdp.edc_management_client
from mvdp.edc_management_client.models.provisioner_webhook_request import ProvisionerWebhookRequest  # noqa: E501
from mvdp.edc_management_client.rest import ApiException

class TestProvisionerWebhookRequest(unittest.TestCase):
    """ProvisionerWebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProvisionerWebhookRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvisionerWebhookRequest`
        """
        model = mvdp.edc_management_client.models.provisioner_webhook_request.ProvisionerWebhookRequest()  # noqa: E501
        if include_optional :
            return ProvisionerWebhookRequest(
                api_key_jwt = '', 
                asset_id = '', 
                content_data_address = mvdp.edc_management_client.models.data_address.DataAddress(
                    properties = {
                        'key' : ''
                        }, ), 
                has_token = True, 
                resource_definition_id = '', 
                resource_name = ''
            )
        else :
            return ProvisionerWebhookRequest(
                api_key_jwt = '',
                asset_id = '',
                content_data_address = mvdp.edc_management_client.models.data_address.DataAddress(
                    properties = {
                        'key' : ''
                        }, ),
                resource_definition_id = '',
                resource_name = '',
        )
        """

    def testProvisionerWebhookRequest(self):
        """Test ProvisionerWebhookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
