# coding: utf-8

# flake8: noqa
"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from mvdp.edc_management_client.models.action import Action
from mvdp.edc_management_client.models.api_error_detail import ApiErrorDetail
from mvdp.edc_management_client.models.asset import Asset
from mvdp.edc_management_client.models.asset_entry_new_dto import AssetEntryNewDto
from mvdp.edc_management_client.models.asset_response_dto import AssetResponseDto
from mvdp.edc_management_client.models.asset_update_request_dto import AssetUpdateRequestDto
from mvdp.edc_management_client.models.callback_address import CallbackAddress
from mvdp.edc_management_client.models.callback_address_dto import CallbackAddressDto
from mvdp.edc_management_client.models.catalog import Catalog
from mvdp.edc_management_client.models.catalog_request_dto import CatalogRequestDto
from mvdp.edc_management_client.models.constraint import Constraint
from mvdp.edc_management_client.models.contract_agreement_dto import ContractAgreementDto
from mvdp.edc_management_client.models.contract_definition_request_dto import ContractDefinitionRequestDto
from mvdp.edc_management_client.models.contract_definition_response_dto import ContractDefinitionResponseDto
from mvdp.edc_management_client.models.contract_negotiation_dto import ContractNegotiationDto
from mvdp.edc_management_client.models.contract_offer import ContractOffer
from mvdp.edc_management_client.models.contract_offer_description import ContractOfferDescription
from mvdp.edc_management_client.models.criterion_dto import CriterionDto
from mvdp.edc_management_client.models.data_address import DataAddress
from mvdp.edc_management_client.models.data_address_dto import DataAddressDto
from mvdp.edc_management_client.models.data_flow_request import DataFlowRequest
from mvdp.edc_management_client.models.data_plane_instance import DataPlaneInstance
from mvdp.edc_management_client.models.data_request_dto import DataRequestDto
from mvdp.edc_management_client.models.data_service import DataService
from mvdp.edc_management_client.models.dataset import Dataset
from mvdp.edc_management_client.models.deprovisioned_resource import DeprovisionedResource
from mvdp.edc_management_client.models.distribution import Distribution
from mvdp.edc_management_client.models.duty import Duty
from mvdp.edc_management_client.models.failure import Failure
from mvdp.edc_management_client.models.health_check_result import HealthCheckResult
from mvdp.edc_management_client.models.health_status import HealthStatus
from mvdp.edc_management_client.models.id_response_dto import IdResponseDto
from mvdp.edc_management_client.models.json_object import JsonObject
from mvdp.edc_management_client.models.json_value import JsonValue
from mvdp.edc_management_client.models.negotiation_initiate_request_dto import NegotiationInitiateRequestDto
from mvdp.edc_management_client.models.negotiation_state import NegotiationState
from mvdp.edc_management_client.models.permission import Permission
from mvdp.edc_management_client.models.policy import Policy
from mvdp.edc_management_client.models.policy_definition_request_dto import PolicyDefinitionRequestDto
from mvdp.edc_management_client.models.policy_definition_response_dto import PolicyDefinitionResponseDto
from mvdp.edc_management_client.models.policy_definition_update_dto import PolicyDefinitionUpdateDto
from mvdp.edc_management_client.models.prohibition import Prohibition
from mvdp.edc_management_client.models.provisioner_webhook_request import ProvisionerWebhookRequest
from mvdp.edc_management_client.models.query_spec_dto import QuerySpecDto
from mvdp.edc_management_client.models.selection_request import SelectionRequest
from mvdp.edc_management_client.models.terminate_transfer_dto import TerminateTransferDto
from mvdp.edc_management_client.models.transfer_process_dto import TransferProcessDto
from mvdp.edc_management_client.models.transfer_process_fail_state_dto import TransferProcessFailStateDto
from mvdp.edc_management_client.models.transfer_request_dto import TransferRequestDto
from mvdp.edc_management_client.models.transfer_state import TransferState
