# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Action(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'constraint': 'Constraint',
        'included_in': 'str',
        'type': 'str'
    }

    attribute_map = {
        'constraint': 'constraint',
        'included_in': 'includedIn',
        'type': 'type'
    }

    def __init__(self, constraint=None, included_in=None, type=None):  # noqa: E501
        """Action - a model defined in Swagger"""  # noqa: E501
        self._constraint = None
        self._included_in = None
        self._type = None
        self.discriminator = None
        if constraint is not None:
            self.constraint = constraint
        if included_in is not None:
            self.included_in = included_in
        if type is not None:
            self.type = type

    @property
    def constraint(self):
        """Gets the constraint of this Action.  # noqa: E501


        :return: The constraint of this Action.  # noqa: E501
        :rtype: Constraint
        """
        return self._constraint

    @constraint.setter
    def constraint(self, constraint):
        """Sets the constraint of this Action.


        :param constraint: The constraint of this Action.  # noqa: E501
        :type: Constraint
        """

        self._constraint = constraint

    @property
    def included_in(self):
        """Gets the included_in of this Action.  # noqa: E501


        :return: The included_in of this Action.  # noqa: E501
        :rtype: str
        """
        return self._included_in

    @included_in.setter
    def included_in(self, included_in):
        """Sets the included_in of this Action.


        :param included_in: The included_in of this Action.  # noqa: E501
        :type: str
        """

        self._included_in = included_in

    @property
    def type(self):
        """Gets the type of this Action.  # noqa: E501


        :return: The type of this Action.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Action.


        :param type: The type of this Action.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Action, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Action):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
