# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ApiErrorDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'invalid_value': 'str',
        'message': 'str',
        'path': 'str',
        'type': 'str'
    }

    attribute_map = {
        'invalid_value': 'invalidValue',
        'message': 'message',
        'path': 'path',
        'type': 'type'
    }

    def __init__(self, invalid_value=None, message=None, path=None, type=None):  # noqa: E501
        """ApiErrorDetail - a model defined in Swagger"""  # noqa: E501
        self._invalid_value = None
        self._message = None
        self._path = None
        self._type = None
        self.discriminator = None
        if invalid_value is not None:
            self.invalid_value = invalid_value
        if message is not None:
            self.message = message
        if path is not None:
            self.path = path
        if type is not None:
            self.type = type

    @property
    def invalid_value(self):
        """Gets the invalid_value of this ApiErrorDetail.  # noqa: E501


        :return: The invalid_value of this ApiErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._invalid_value

    @invalid_value.setter
    def invalid_value(self, invalid_value):
        """Sets the invalid_value of this ApiErrorDetail.


        :param invalid_value: The invalid_value of this ApiErrorDetail.  # noqa: E501
        :type: str
        """

        self._invalid_value = invalid_value

    @property
    def message(self):
        """Gets the message of this ApiErrorDetail.  # noqa: E501


        :return: The message of this ApiErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ApiErrorDetail.


        :param message: The message of this ApiErrorDetail.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def path(self):
        """Gets the path of this ApiErrorDetail.  # noqa: E501


        :return: The path of this ApiErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ApiErrorDetail.


        :param path: The path of this ApiErrorDetail.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def type(self):
        """Gets the type of this ApiErrorDetail.  # noqa: E501


        :return: The type of this ApiErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ApiErrorDetail.


        :param type: The type of this ApiErrorDetail.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiErrorDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
