# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from mvdp.edc_management_client.models.asset import Asset
from mvdp.edc_management_client.models.data_address import DataAddress

class AssetEntryNewDto(BaseModel):
    """
    AssetEntryNewDto
    """
    asset: Asset = Field(...)
    data_address: DataAddress = Field(..., alias="dataAddress")
    __properties = ["asset", "dataAddress"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AssetEntryNewDto:
        """Create an instance of AssetEntryNewDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of asset
        if self.asset:
            _dict['asset'] = self.asset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_address
        if self.data_address:
            _dict['dataAddress'] = self.data_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AssetEntryNewDto:
        """Create an instance of AssetEntryNewDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AssetEntryNewDto.parse_obj(obj)

        _obj = AssetEntryNewDto.parse_obj({
            "asset": Asset.from_dict(obj.get("asset")) if obj.get("asset") is not None else None,
            "data_address": DataAddress.from_dict(obj.get("dataAddress")) if obj.get("dataAddress") is not None else None
        })
        return _obj

