# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Constraint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'edctype': 'str'
    }

    attribute_map = {
        'edctype': 'edctype'
    }

    discriminator_value_class_map = {
    }

    def __init__(self, edctype=None):  # noqa: E501
        """Constraint - a model defined in Swagger"""  # noqa: E501
        self._edctype = None
        self.discriminator = 'edctype'
        self.edctype = edctype

    @property
    def edctype(self):
        """Gets the edctype of this Constraint.  # noqa: E501


        :return: The edctype of this Constraint.  # noqa: E501
        :rtype: str
        """
        return self._edctype

    @edctype.setter
    def edctype(self, edctype):
        """Sets the edctype of this Constraint.


        :param edctype: The edctype of this Constraint.  # noqa: E501
        :type: str
        """
        if edctype is None:
            raise ValueError("Invalid value for `edctype`, must not be `None`")  # noqa: E501

        self._edctype = edctype

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Constraint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Constraint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
