# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from mvdp.edc_management_client.models.policy import Policy

class ContractOfferDescription(BaseModel):
    """
    ContractOfferDescription
    """
    asset_id: StrictStr = Field(..., alias="assetId")
    offer_id: StrictStr = Field(..., alias="offerId")
    policy: Policy = Field(...)
    validity: Optional[StrictInt] = None
    __properties = ["assetId", "offerId", "policy", "validity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContractOfferDescription:
        """Create an instance of ContractOfferDescription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContractOfferDescription:
        """Create an instance of ContractOfferDescription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContractOfferDescription.parse_obj(obj)

        _obj = ContractOfferDescription.parse_obj({
            "asset_id": obj.get("assetId"),
            "offer_id": obj.get("offerId"),
            "policy": Policy.from_dict(obj.get("policy")) if obj.get("policy") is not None else None,
            "validity": obj.get("validity")
        })
        return _obj

