# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ContractOfferDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'str',
        'offer_id': 'str',
        'policy': 'Policy',
        'validity': 'int'
    }

    attribute_map = {
        'asset_id': 'assetId',
        'offer_id': 'offerId',
        'policy': 'policy',
        'validity': 'validity'
    }

    def __init__(self, asset_id=None, offer_id=None, policy=None, validity=None):  # noqa: E501
        """ContractOfferDescription - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._offer_id = None
        self._policy = None
        self._validity = None
        self.discriminator = None
        self.asset_id = asset_id
        self.offer_id = offer_id
        self.policy = policy
        if validity is not None:
            self.validity = validity

    @property
    def asset_id(self):
        """Gets the asset_id of this ContractOfferDescription.  # noqa: E501


        :return: The asset_id of this ContractOfferDescription.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this ContractOfferDescription.


        :param asset_id: The asset_id of this ContractOfferDescription.  # noqa: E501
        :type: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def offer_id(self):
        """Gets the offer_id of this ContractOfferDescription.  # noqa: E501


        :return: The offer_id of this ContractOfferDescription.  # noqa: E501
        :rtype: str
        """
        return self._offer_id

    @offer_id.setter
    def offer_id(self, offer_id):
        """Sets the offer_id of this ContractOfferDescription.


        :param offer_id: The offer_id of this ContractOfferDescription.  # noqa: E501
        :type: str
        """
        if offer_id is None:
            raise ValueError("Invalid value for `offer_id`, must not be `None`")  # noqa: E501

        self._offer_id = offer_id

    @property
    def policy(self):
        """Gets the policy of this ContractOfferDescription.  # noqa: E501


        :return: The policy of this ContractOfferDescription.  # noqa: E501
        :rtype: Policy
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this ContractOfferDescription.


        :param policy: The policy of this ContractOfferDescription.  # noqa: E501
        :type: Policy
        """
        if policy is None:
            raise ValueError("Invalid value for `policy`, must not be `None`")  # noqa: E501

        self._policy = policy

    @property
    def validity(self):
        """Gets the validity of this ContractOfferDescription.  # noqa: E501


        :return: The validity of this ContractOfferDescription.  # noqa: E501
        :rtype: int
        """
        return self._validity

    @validity.setter
    def validity(self, validity):
        """Sets the validity of this ContractOfferDescription.


        :param validity: The validity of this ContractOfferDescription.  # noqa: E501
        :type: int
        """

        self._validity = validity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContractOfferDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContractOfferDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
