# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DataRequestDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'str',
        'connector_id': 'str',
        'contract_id': 'str',
        'id': 'str'
    }

    attribute_map = {
        'asset_id': 'assetId',
        'connector_id': 'connectorId',
        'contract_id': 'contractId',
        'id': 'id'
    }

    def __init__(self, asset_id=None, connector_id=None, contract_id=None, id=None):  # noqa: E501
        """DataRequestDto - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._connector_id = None
        self._contract_id = None
        self._id = None
        self.discriminator = None
        if asset_id is not None:
            self.asset_id = asset_id
        if connector_id is not None:
            self.connector_id = connector_id
        if contract_id is not None:
            self.contract_id = contract_id
        if id is not None:
            self.id = id

    @property
    def asset_id(self):
        """Gets the asset_id of this DataRequestDto.  # noqa: E501


        :return: The asset_id of this DataRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this DataRequestDto.


        :param asset_id: The asset_id of this DataRequestDto.  # noqa: E501
        :type: str
        """

        self._asset_id = asset_id

    @property
    def connector_id(self):
        """Gets the connector_id of this DataRequestDto.  # noqa: E501


        :return: The connector_id of this DataRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._connector_id

    @connector_id.setter
    def connector_id(self, connector_id):
        """Sets the connector_id of this DataRequestDto.


        :param connector_id: The connector_id of this DataRequestDto.  # noqa: E501
        :type: str
        """

        self._connector_id = connector_id

    @property
    def contract_id(self):
        """Gets the contract_id of this DataRequestDto.  # noqa: E501


        :return: The contract_id of this DataRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._contract_id

    @contract_id.setter
    def contract_id(self, contract_id):
        """Sets the contract_id of this DataRequestDto.


        :param contract_id: The contract_id of this DataRequestDto.  # noqa: E501
        :type: str
        """

        self._contract_id = contract_id

    @property
    def id(self):
        """Gets the id of this DataRequestDto.  # noqa: E501


        :return: The id of this DataRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataRequestDto.


        :param id: The id of this DataRequestDto.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataRequestDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataRequestDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
