# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class DataPlaneInstance(BaseModel):
    """
    DataPlaneInstance
    """
    allowed_dest_types: Optional[conlist(StrictStr, unique_items=True)] = Field(None, alias="allowedDestTypes")
    allowed_source_types: Optional[conlist(StrictStr, unique_items=True)] = Field(None, alias="allowedSourceTypes")
    id: Optional[StrictStr] = None
    last_active: Optional[StrictInt] = Field(None, alias="lastActive")
    properties: Optional[Dict[str, Dict[str, Any]]] = None
    turn_count: Optional[StrictInt] = Field(None, alias="turnCount")
    url: Optional[StrictStr] = None
    __properties = ["allowedDestTypes", "allowedSourceTypes", "id", "lastActive", "properties", "turnCount", "url"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DataPlaneInstance:
        """Create an instance of DataPlaneInstance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DataPlaneInstance:
        """Create an instance of DataPlaneInstance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DataPlaneInstance.parse_obj(obj)

        _obj = DataPlaneInstance.parse_obj({
            "allowed_dest_types": obj.get("allowedDestTypes"),
            "allowed_source_types": obj.get("allowedSourceTypes"),
            "id": obj.get("id"),
            "last_active": obj.get("lastActive"),
            "properties": obj.get("properties"),
            "turn_count": obj.get("turnCount"),
            "url": obj.get("url")
        })
        return _obj

