# coding: utf-8

"""
    EDC REST API

    EDC REST APIs - merged by OpenApiMerger  # noqa: E501

    The version of the OpenAPI document: 0.1.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, conlist
from mvdp.edc_management_client.models.health_check_result import HealthCheckResult

class HealthStatus(BaseModel):
    """
    HealthStatus
    """
    component_results: Optional[conlist(HealthCheckResult)] = Field(None, alias="componentResults")
    is_system_healthy: Optional[StrictBool] = Field(None, alias="isSystemHealthy")
    __properties = ["componentResults", "isSystemHealthy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HealthStatus:
        """Create an instance of HealthStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in component_results (list)
        _items = []
        if self.component_results:
            for _item in self.component_results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['componentResults'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HealthStatus:
        """Create an instance of HealthStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HealthStatus.parse_obj(obj)

        _obj = HealthStatus.parse_obj({
            "component_results": [HealthCheckResult.from_dict(_item) for _item in obj.get("componentResults")] if obj.get("componentResults") is not None else None,
            "is_system_healthy": obj.get("isSystemHealthy")
        })
        return _obj

