# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SelectionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'destination': 'DataAddress',
        'source': 'DataAddress',
        'strategy': 'str'
    }

    attribute_map = {
        'destination': 'destination',
        'source': 'source',
        'strategy': 'strategy'
    }

    def __init__(self, destination=None, source=None, strategy=None):  # noqa: E501
        """SelectionRequest - a model defined in Swagger"""  # noqa: E501
        self._destination = None
        self._source = None
        self._strategy = None
        self.discriminator = None
        if destination is not None:
            self.destination = destination
        if source is not None:
            self.source = source
        if strategy is not None:
            self.strategy = strategy

    @property
    def destination(self):
        """Gets the destination of this SelectionRequest.  # noqa: E501


        :return: The destination of this SelectionRequest.  # noqa: E501
        :rtype: DataAddress
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this SelectionRequest.


        :param destination: The destination of this SelectionRequest.  # noqa: E501
        :type: DataAddress
        """

        self._destination = destination

    @property
    def source(self):
        """Gets the source of this SelectionRequest.  # noqa: E501


        :return: The source of this SelectionRequest.  # noqa: E501
        :rtype: DataAddress
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this SelectionRequest.


        :param source: The source of this SelectionRequest.  # noqa: E501
        :type: DataAddress
        """

        self._source = source

    @property
    def strategy(self):
        """Gets the strategy of this SelectionRequest.  # noqa: E501


        :return: The strategy of this SelectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._strategy

    @strategy.setter
    def strategy(self, strategy):
        """Sets the strategy of this SelectionRequest.


        :param strategy: The strategy of this SelectionRequest.  # noqa: E501
        :type: str
        """

        self._strategy = strategy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SelectionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SelectionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
