# coding: utf-8

"""
    management-api

    REST API documentation for the management-api  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TransferType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content_type': 'str',
        'is_finite': 'bool'
    }

    attribute_map = {
        'content_type': 'contentType',
        'is_finite': 'isFinite'
    }

    def __init__(self, content_type=None, is_finite=None):  # noqa: E501
        """TransferType - a model defined in Swagger"""  # noqa: E501
        self._content_type = None
        self._is_finite = None
        self.discriminator = None
        if content_type is not None:
            self.content_type = content_type
        if is_finite is not None:
            self.is_finite = is_finite

    @property
    def content_type(self):
        """Gets the content_type of this TransferType.  # noqa: E501


        :return: The content_type of this TransferType.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this TransferType.


        :param content_type: The content_type of this TransferType.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def is_finite(self):
        """Gets the is_finite of this TransferType.  # noqa: E501


        :return: The is_finite of this TransferType.  # noqa: E501
        :rtype: bool
        """
        return self._is_finite

    @is_finite.setter
    def is_finite(self, is_finite):
        """Sets the is_finite of this TransferType.


        :param is_finite: The is_finite of this TransferType.  # noqa: E501
        :type: bool
        """

        self._is_finite = is_finite

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransferType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
